import antfu from '@antfu/eslint-config'

export default antfu({
  // enable UnoCSS support
  // https://unocss.dev/integrations/vscode
  unocss: true,
  // files: [
  //   '**/*.ts',
  //   '**/*.vue',
  // ],
  ignores: [
    '.github/**',
    'scripts/**',
    'dist',
    'dev-dist',
    '**/dist/**',
    'node_modules',
    '**/node_modules/**',
    'public',
    '**/public/**',
    '.husky',
    '**/.husky/**',
    '.vscode',
    '**/.vscode/**',
    '.idea',
    '**/.idea/**',
    '*.sh',
    '**/*.sh/**',
    '*.md',
    '**/*.md',
    '**/*.md/**',
    'src/assets',
    'src/assets/**',
    '.eslintrc.cjs',
    '**/.eslintrc.cjs/**',
    '.prettierrc.cjs',
    '**/.prettierrc.cjs/**',
    '.stylelintrc.cjs',
    '**/.stylelintrc.cjs/**',
    'src/02-kk-i18n-system/**/*.js',
    'src/02-kk-i18n-admin/**/*.js',
    'src/01-kk-system/**/*.js',
    'src/04-kk-component-mobile/**/*.js',
  ],

  formatters: {
    css: true,
  },

  stylistic: true, // enable stylistic formatting rules
  typescript: true,
  vue: true,
  jsonc: false,

  rules: {
    'no-console': 'off',
    'prefer-promise-reject-errors': ['error', {
      allowEmptyReject: true,
    }],
    'no-irregular-whitespace': ['error', { skipStrings: true }],
    'regexp/no-unused-capturing-group': [0, {
      fixable: true,
      allowNamed: true,
    }],
  },
}, {
  ignores: [
    '.github/**',
    'scripts/**',
    'dist',
    'dev-dist',
    '**/dist/**',
    'node_modules',
    '**/node_modules/**',
    'public',
    '**/public/**',
    '.husky',
    '**/.husky/**',
    '.vscode',
    '**/.vscode/**',
    '.idea',
    '**/.idea/**',
    '*.sh',
    '**/*.sh/**',
    '*.md',
    '**/*.md',
    '**/*.md/**',
    'src/assets',
    'src/assets/**',
    '.eslintrc.cjs',
    '**/.eslintrc.cjs/**',
    '.prettierrc.cjs',
    '**/.prettierrc.cjs/**',
    '.stylelintrc.cjs',
    '**/.stylelintrc.cjs/**',
    'src/02-kk-i18n-system/**/*.js',
    'src/02-kk-i18n-admin/**/*.js',
    'src/01-kk-system/**/*.js',
    'src/04-kk-component-mobile/**/*.js',
  ],
})
