export const HotGame = [
  {
    logo: '/_always_win_/lobby/logo/classify/content/CN-101.png',
    lottoID: '2004',
    name: '奇趣分分彩',
    country: 'CN',
    lottoClassify: '101',
    webSite: 'https://77tj.org',
    status: '1',
    statusPlatform: '1',
    source: 'third',
  },
  {
    logo: '/_always_win_/lobby/logo/classify/content/CN-101.png',
    lottoID: '2003',
    name: 'QQ分分彩',
    country: 'CN',
    lottoClassify: '101',
    webSite: 'https://77tj.org',
    status: '1',
    statusPlatform: '1',
    source: 'third',
  },
  {
    logo: '/_always_win_/lobby/logo/classify/content/CN-101.png',
    lottoID: '3001',
    name: '波场分分彩',
    country: 'CN',
    lottoClassify: '101',
    webSite: 'https://tronscan.org/#/',
    status: '1',
    statusPlatform: '1',
    source: 'third',
  },
  {
    logo: '/_always_win_/lobby/logo/classify/content/CN-101.png',
    lottoID: '1001',
    name: '澳洲幸运5',
    country: 'CN',
    lottoClassify: '101',
    webSite: 'https://1689615.com/view/aozxy5/ssc_index.html',
    status: '1',
    statusPlatform: '1',
    source: 'third',
  },
  {
    logo: '/_always_win_/lobby/logo/classify/content/CN-107.png',
    lottoID: '1005',
    name: '福彩3D',
    country: 'CN',
    lottoClassify: '107',
    webSite: 'https://1689615.com/view/wanfaguize/FCSD.html',
    status: '1',
    statusPlatform: '1',
    source: 'third',
  },
]
